version: '3.8'

services:
  backend:
    build: .
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
